Fix BCAddressField where field is required but there is no value
If the field matches above conditions, validation will raise an AttributeError:

...
File ".../python2.7/site-packages/django/forms/forms.py", line 287, in _clean_fields
    value = field.clean(value)
  File ".../python2.7/site-packages/django_bitcoin/BCAddressField.py", line 21, in clean
    value = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'